---
title: "alignment_comparison"
format: html
---

```{r}
setwd("D:/data_kingston/data_bueno/scripts/ampliseq_analysis")
#read alignment stats 
align_msc <- read.csv("comparacion_alineamiento_msc.csv")
align_wat <- read.csv("comparacion_alineamiento_scwat.csv")

#load libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
```

```{r}
#idea de tutora
#reshape dataset to long 
msc_long <- align_msc %>%
  select(sample, total_reads, alignment_rate, mapped_reads, mismatch_rate, aligner) %>%
  pivot_longer(cols = c(total_reads, alignment_rate, mapped_reads, mismatch_rate),
               names_to = "Stage", values_to = "Reads" )

wat_long <- align_wat %>%
  select(sample, total_reads, alignment_rate, mapped_reads, mismatch_rate, aligner) %>%
  pivot_longer(cols = c(total_reads, alignment_rate, mapped_reads, mismatch_rate),
               names_to = "Stage", values_to = "Reads")

#line plot to visualize
ggplot(msc_long, aes(x = Stage, y = Reads, group = sample, colour = aligner)) +
  geom_line(size= 1) +
  geom_point( size= 1)
  theme_minimal()
```

```{r}
#mi idea inicial
ggplot(align_msc, aes(x= aligner, y= alignment_rate, fill = aligner)) +
  geom_boxplot() +
  theme_minimal() 

ggplot(align_wat, aes(x= aligner, y= alignment_rate, fill = aligner)) +
  geom_boxplot() +
  theme_minimal() 
```

```{r}
#igual puedo adaptar lo que me dice mi tutora a esto, y añadirlo a los boxplots
msc_reads <- align_msc %>%
  select(sample, aligner, total_reads, mapped_reads) %>% 
  pivot_longer(cols = c(total_reads, mapped_reads),
               names_to = "Stage", values_to = "Reads")
ggplot(msc_reads, aes(x= Stage, y= Reads, group = sample, color= aligner))+
  geom_line(size = 1) +
  geom_point(size = 1) +
  theme_minimal()

#habría que invertir el orden para que primero salgan las total reads
```
